ANNOTATION_TYPE_KEY = "annotation_type"
N3D_METADATA_KEY = "n3d_metadata"

POINT_ANNOTATION_TYPE_KEY = "points"
SPHERE_ANNOTATION_TYPE_KEY = "spheres"
SPLINE_ANNOTATION_TYPE_KEY = "splines"
SURFACE_ANNOTATION_TYPE_KEY = "surfaces"
